import React, { createContext, useContext, useState } from 'react';

export type Language = 'en' | 'ar';
export type Currency = 'USD' | 'SAR' | 'EGP' | 'AED';

interface LanguageContextType {
  language: Language;
  currency: Currency;
  setLanguage: (language: Language) => void;
  setCurrency: (currency: Currency) => void;
  t: (key: string) => string;
  getCurrencySymbol: (curr?: Currency) => string;
}

const translations = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.dashboard': 'Dashboard',
    'nav.products': 'Products',
    'nav.analytics': 'Analytics',
    'nav.news': 'News & Updates',
    'nav.events': 'Events',
    'nav.promoCodes': 'Promo Codes',
    'nav.donation': 'Support Krolist',
    'nav.myOrders': 'My Orders',
    'nav.settings': 'Settings',
    'nav.categories': 'Categories',
    'nav.articles': 'Articles',
    'nav.addProduct': 'Add Product',
    
    // Home
    'home.welcome': 'Welcome to Krolist',
    'home.subtitle': 'Discover the best deals across all your favorite stores',
    'home.startShopping': 'Start Shopping',
    'home.myProducts': 'My Products',
    'home.featured': 'Featured Products',
    'home.categories': 'Shop by Category',
    'home.viewAll': 'View All',
    'home.noCategoryProducts': 'No products in this category yet',
    
    // Dashboard
    'dashboard.welcome': 'Welcome to PriceTracker',
    'dashboard.subtitle': 'Track your favorite products and never miss a deal again',
    'dashboard.totalProducts': 'Total Products',
    'dashboard.priceDrops': 'Price Drops',
    'dashboard.priceIncreases': 'Price Increases',
    'dashboard.totalAmount': 'Total Amount of Products',
    'dashboard.watching': 'Watching',
    'dashboard.recentAlerts': 'Recent Price Change',
    'dashboard.latestChanges': 'Latest price changes on your tracked products',
    'dashboard.overview': 'Overview',
    
    // Products
    'products.title': 'Your Products',
    'products.subtitle': 'Track and manage your favorite products',
    'products.noProducts': 'No products tracked yet',
    'products.startTracking': 'Start tracking products to see them here',
    'products.searchProducts': 'Search Products',
    'products.manualEntry': 'Manual Entry',
    'products.viewDetails': 'View Details',
    'products.searchPlaceholder': 'Search products, stores, or categories...',
    'products.noResults': 'No products found',
    'products.noResultsDesc': 'Try adjusting your search terms',
    'products.delete': 'Delete',
    'products.currency': 'Currency',
    'products.refresh': 'Refresh',
    'products.edit': 'Edit',
    'products.description': 'Experience immersive sound quality with noise cancellation.',
    'products.updated': 'Updated',
    'products.showHistory': 'Show history',
    'products.priceDetails': 'Price Details',
    'products.recordedHistory': 'Recorded price history over the last 7 months',
    'products.highest': 'Highest',
    'products.lowest': 'Lowest',
    'products.original': 'Original',
    'products.deleteSuccess': 'Product deleted successfully',
    'products.currencyChanged': 'Currency changed successfully',
    'products.editSuccess': 'Product updated successfully',
    'products.changeCurrency': 'Change Currency',
    'products.selectCurrency': 'Select the currency for this product',
    'products.editProduct': 'Edit Product',
    'products.select': 'Add to cart',
    'products.cancelSelection': 'Cancel',
    'products.addToCart': 'Add to Cart',
    'products.selectedItems': 'items selected',
    'products.selectSameStore': 'Please select products from the same store only',
    'products.editDescription': 'Update the product details below',
    'products.productTitle': 'Product Title',
    'products.enterTitle': 'Enter product title',
    'products.productDescription': 'Product Description',
    'products.enterDescription': 'Enter product description',
    'products.imageUrl': 'Image URL',
    'products.enterImageUrl': 'Enter image URL',
    'products.currentPrice': 'Current Price',
    'products.enterPrice': 'Enter price',
    'products.addProduct': 'Add a Product',
    'products.addProductDesc': 'Choose how you\'d like to add a product to track',
    'products.searchForProducts': 'Search for Products',
    'products.searchProductsDesc': 'Search across multiple stores and compare prices from different sellers',
    'products.more': 'More...',
    'products.addManually': 'Add Manually',
    'products.addManuallyDesc': 'Paste a product URL and we\'ll auto-fill the details, or enter everything manually',
    'products.anyURL': 'Any URL',
    'products.fullControl': 'Full Control',
    'products.displayMode': 'Display',
    'products.fullImage': 'Full Image',
    'products.cropped': 'Cropped',
    'products.history': 'History',
    
    // Settings
    'settings.title': 'Settings',
    'settings.subtitle': 'Manage your account preferences and app settings',
    'settings.languageRegion': 'Language & Region',
    'settings.languageDesc': 'Configure your preferred language and default currency',
    'settings.language': 'Language',
    'settings.currency': 'Default Currency',
    'settings.notifications': 'Notifications',
    'settings.notificationsDesc': 'Choose what notifications you want to receive',
    'settings.enableNotifications': 'Enable Notifications',
    'settings.enableNotificationsDesc': 'Receive notifications about price changes and updates',
    'settings.priceDropAlerts': 'Price Drop Alerts',
    'settings.priceDropAlertsDesc': 'Get notified when tracked product prices decrease',
    'settings.weeklyReports': 'Weekly Reports',
    'settings.weeklyReportsDesc': 'Receive weekly summaries of your tracked products',
    'settings.appearance': 'Appearance',
    'settings.appearanceDesc': 'Click for light or dark view',
    'settings.theme': 'Theme',
    'settings.account': 'Account',
    'settings.accountDesc': 'Manage your account information',
    'settings.email': 'Email',
    'settings.displayName': 'Display Name',
    'settings.saveSettings': 'Save Settings',
    'settings.settingsSaved': 'Settings Saved',
    'settings.settingsSavedDesc': 'Your preferences have been updated successfully.',
    'settings.undertoneColor': 'Undertone Color',
    'settings.selectUndertone': 'Select undertone',
    'settings.undertone.orange': 'Orange',
    'settings.undertone.blue': 'Blue',
    'settings.undertone.green': 'Green',
    'settings.undertone.purple': 'Purple',
    'settings.undertone.red': 'Red',
    'settings.undertone.custom': 'Custom',
    'settings.imageZoom': 'Image Zoom on Hover',
    'settings.imageZoomDesc': 'Enable zoom effect',
    'settings.carouselSpeed': 'Carousel Auto-Scroll Speed',
    'settings.carouselSpeedDesc': 'Lower = faster scrolling',
    'settings.titleScrollSpeed': 'Product Title Scroll Speed',
    'settings.customHue': 'Custom Hue',
    'settings.languageCurrency': 'Language & Currency',
    'settings.username': 'Username',
    'settings.usernamePlaceholder': 'Your Username',
    'settings.updating': 'Updating...',
    'settings.updateAccount': 'Update Account',
    'settings.profileUpdated': 'Profile updated successfully!',
    'settings.profileUpdatedEmail': 'Profile updated! Please check your new email to confirm the change.',
    'settings.failedUpdate': 'Failed to update profile',
    'settings.notSupported': 'Not Supported',
    'settings.browserNoNotifications': "Your browser doesn't support notifications",
    'settings.notificationsEnabled': 'Notifications Enabled',
    'settings.notifiedAboutUpdates': "You'll be notified about updates",
    'settings.appInfo': 'App Info',
    'settings.versionUpdates': 'Version and updates',
    'settings.currentVersion': 'Current Version',
    'settings.installUpdate': 'Install Update',
    'settings.upToDate': 'Up to date',
    'settings.totalInstalls': 'Total Installs',
    'settings.usersInstalled': 'Users who installed the app',
    'settings.updateNotifications': 'Update Notifications',
    'settings.updateNotificationsDesc': 'Get notified when a new update is available',
    'settings.enabled': 'Enabled',
    'settings.enable': 'Enable',
    'settings.promoAlerts': 'Promo Code Alerts',
    'settings.promoAlertsDesc': 'Get notified about new promo codes and deals',
    'settings.appUpdateAlerts': 'App Update Alerts',
    'settings.appUpdateAlertsDesc': 'Get notified when new app features are available',
    'settings.eventReminders': 'Event Reminders',
    'settings.eventRemindersDesc': 'Get reminded about shopping events like Black Friday',
    'settings.orderUpdates': 'Order Updates',
    'settings.orderUpdatesDesc': 'Get notified about your order status changes',
    'settings.articleAlerts': 'New Article Alerts',
    'settings.articleAlertsDesc': 'Get notified when new articles are published',
    
    // Common
    'loading': 'Loading...',
    'error': 'Error',
    'save': 'Save',
    'cancel': 'Cancel',
    'success': 'Success',
    'featured': 'Featured',
    'add': 'Add',
    'edit': 'Edit',
    'delete': 'Delete',
    'remove': 'Remove',
    'update': 'Update',
    'search': 'Search',
    'filter': 'Filter',
    'view': 'View',
    'close': 'Close',
    'open': 'Open',
    'create': 'Create',
    'submit': 'Submit',
    'confirm': 'Confirm',
    'back': 'Back',
    'next': 'Next',
    'apply': 'Apply',
    'reset': 'Reset',
    'clear': 'Clear',
    
    // Categories
    'categories.title': 'Categories',
    'categories.subtitle': 'Browse products by category',
    'categories.empty': 'No categories available yet',
    'categories.viewAll': 'View All',
    'categories.items': 'items',
    
    // Promo Codes Page
    'promo.title': 'Promo Codes',
    'promo.subtitle': 'Manage your collection of discount codes and coupons',
    'promo.addNew': 'Add New Promo Code',
    'promo.addNewDesc': 'Save promo codes you find online for easy access when shopping',
    'promo.code': 'Promo Code',
    'promo.codePlaceholder': 'SAVE20',
    'promo.shop': 'Shop',
    'promo.selectShop': 'Select a shop',
    'promo.customShopName': 'Custom Shop Name',
    'promo.enterShopName': 'Enter shop name',
    'promo.description': 'Description',
    'promo.descriptionPlaceholder': '20% off electronics',
    'promo.addCode': 'Add Code',
    'promo.codeCopied': 'Code Copied!',
    'promo.codeCopiedDesc': 'Promo code copied to clipboard',
    'promo.authRequired': 'Authentication Required',
    'promo.signInToAdd': 'Please sign in to add promo codes',
    'promo.missingInfo': 'Missing Information',
    'promo.fillAllFields': 'Please fill in all required fields',
    'promo.limitReached': 'Limit Reached',
    'promo.limitReachedDesc': 'You can only save up to 24 promo codes',
    'promo.codeAdded': 'Promo Code Added!',
    'promo.codeAddedDesc': 'Your promo code has been saved to your collection',
    'promo.codeUpdated': 'Promo Code Updated!',
    'promo.changesSaved': 'Your changes have been saved',
    'promo.codeDeleted': 'Promo Code Deleted',
    'promo.codeDeletedDesc': 'The promo code has been removed from your collection',
    'promo.failedToLoad': 'Failed to load promo codes',
    'promo.failedToAdd': 'Failed to add promo code',
    'promo.failedToUpdate': 'Failed to update promo code',
    'promo.failedToDelete': 'Failed to delete promo code',
    'promo.reusable': 'Reusable',
    'promo.oneTimeUse': 'One-time use',
    'promo.used': 'Used',
    'promo.expires': 'Expires',
    'promo.copy': 'Copy',
    'promo.editPromo': 'Edit Promo Code',
    'promo.editPromoDesc': 'Update your promo code details below',
    'promo.store': 'Store',
    'promo.makeReusable': 'Make Reusable',
    'promo.saveChanges': 'Save Changes',
    'promo.noPersonalCodes': 'No personal promo codes yet',
    'promo.startSaving': 'Start saving promo codes you find online for easy access when shopping',
    'promo.wantToSave': 'Want to Save Your Own Promo Codes?',
    'promo.createAccountToSave': 'Create an account to save and manage your personal promo codes collection. Click the user icon in the top right to sign up or log in.',
    'promo.expired': 'Expired',
    'promo.expiresToday': 'Expires today',
    'promo.dayLeft': '1 day left',
    'promo.daysLeft': 'days left',
    'promo.unknown': 'Unknown',
    'promo.expirationDate': 'Expiration Date',
    'promo.expirationHint': 'Leave empty for 1 year',
    'promo.usageType': 'Usage Type',
    'promo.storeImage': 'Store Image',
    'promo.addImage': 'Add',
    'promo.changeImage': 'Change',
    'promo.saving': 'Saving...',
    
    
    // Admin Dashboard
    'admin.dashboard': 'Admin Dashboard',
    'admin.dashboardDesc': 'Manage Krolist content and settings',
    'admin.accessDenied': 'Access Denied',
    'admin.accessDeniedDesc': 'You need admin privileges to access this page',
    'admin.krolistProducts': 'Krolist Products',
    'admin.krolistProductsDesc': 'Manage curated product selections for all users',
    'admin.promoCodes': 'Promo Codes',
    'admin.krolistPromoCodes': 'Krolist Promo Codes',
    'admin.krolistPromoCodesDesc': 'Manage promo codes visible to all users',
    'admin.newsUpdates': 'News & Updates',
    'admin.newsUpdatesDesc': 'Manage news and announcements',
    'admin.shopManagement': 'Shop Management',
    'admin.shopManagementDesc': 'Manage available shops and affiliate links',
    'admin.addProduct': 'Add Product',
    'admin.manualPrices': 'Manual Prices',
    'admin.editProduct': 'Edit Product',
    'admin.addPromoCode': 'Add Promo Code',
    'admin.editPromoCode': 'Edit Promo Code',
    'admin.addNews': 'Add News',
    'admin.editNews': 'Edit News',
    'admin.confirmDelete': 'Are you sure you want to delete this?',
    'admin.productAdded': 'Product added successfully',
    'admin.productUpdated': 'Product updated successfully',
    'admin.productDeleted': 'Product deleted successfully',
    'admin.promoCodeAdded': 'Promo code added successfully',
    'admin.promoCodeUpdated': 'Promo code updated successfully',
    'admin.promoCodeDeleted': 'Promo code deleted successfully',
    'admin.newsAdded': 'News added successfully',
    'admin.newsUpdated': 'News updated successfully',
    'admin.newsDeleted': 'News deleted successfully',
    'admin.contentSaved': 'Content saved successfully',
    'admin.noChanges': 'No changes to save',
    'admin.mustBeLoggedIn': 'You must be logged in',
    'admin.failedToLoadPromoCodes': 'Failed to load promo codes',
    'admin.titleEnglish': 'Title (English)',
    'admin.titleArabic': 'Title (Arabic)',
    'admin.contentEnglish': 'Content (English)',
    'admin.contentArabic': 'Content (Arabic)',
    'admin.category': 'Category',
    'admin.publishNow': 'Publish Now',
    'admin.draft': 'Draft',
    'admin.published': 'Published',
    'admin.featured': 'Featured',
    'admin.saveAll': 'Save All',
    'admin.searchContent': 'Search content...',
    'admin.allCategories': 'All Categories',
    'admin.modified': 'Modified',
    'admin.englishText': 'English Text',
    'admin.arabicText': 'Arabic Text',
    'admin.noContentFound': 'No content found',
    
    // Filters
    'filters.title': 'Filter Products',
    'filters.priceRange': 'Price Range',
    'filters.upTo': 'Up to',
    'filters.categories': 'Categories',
    'filters.stores': 'Stores',
    'filters.clearAll': 'Clear All Filters',
    
    // Product Fields
    'product.title': 'Title',
    'product.description': 'Description',
    'product.imageUrl': 'Image URL',
    'product.category': 'Category',
    'product.customCategory': 'Custom Category',
    'product.customCategoryPlaceholder': 'Enter custom category (max 16 chars)',
    'product.currentPrice': 'Current Price',
    'product.originalPrice': 'Original Price',
    'product.currency': 'Currency',
    'product.originalCurrency': 'Original Currency',
    'product.store': 'Store',
    'product.productUrl': 'Product URL',
    'product.editProduct': 'Edit Product',
    
    // News Categories
    'news.announcement': 'Announcement',
    'news.feature': 'Feature',
    'news.update': 'Update',
    
    // Theme options
    'theme.light': 'Light',
    'theme.dark': 'Dark',
    'theme.system': 'System',
    
    // Languages
    'language.en': 'English',
    'language.ar': 'العربية',
    
    // Currencies
    'currency.USD': 'USD - US Dollar',
    'currency.SAR': 'SAR - Saudi Riyal',
    'currency.EGP': 'EGP - Egyptian Pound',
    'currency.AED': 'AED - UAE Dirham',

    // Analytics
    'analytics.trends': 'Price Trends',
    'analytics.stores': 'Store Performance',
    'analytics.categories': 'Categories',
    'analytics.patterns': 'Price Patterns',
    'analytics.trendsDesc': 'Track price movements over time',
    'analytics.storesDesc': 'Compare store savings and reliability',
    'analytics.categoriesDesc': 'Analyze products by category',
    'analytics.patternsDesc': 'Discover when prices drop most',
    'analytics.avgSavings': 'Avg Savings',
    'analytics.reliability': 'Reliability',
    
    // Products Page
    'products.myProducts': 'MY PRODUCTS',
    'products.featuredProducts': 'FEATURED PRODUCTS',
    'products.krolistSelections': 'KROLIST SELECTIONS',
    'products.expand': 'Expand',
    'products.collapse': 'Collapse',
    
    // UI Controls
    'ui.fontSize': 'Font Size',
    'ui.iconSize': 'Icon Size',
    'ui.display': 'Display',
    'ui.displayDesc': 'Customize font and icon sizes',
    'ui.small': 'Small',
    'ui.medium': 'Medium',
    'ui.large': 'Large',
    
    // Events
    'events.upcoming': 'Upcoming Events',

    // Shop Management
    'settings.shopManagement': 'Shop Management',
    'settings.shopManagementDesc': 'Organize and customize your tracked shops',
    'settings.addNewShop': 'Add new shop...',
    'settings.dragToReorder': 'Drag to reorder',
    'status.active': 'Active',
    'search.placeholder': 'Search shops...',

    // Shops
    'shops.shein': 'SHEIN',
    'shops.noon': 'NOON',
    'shops.amazon': 'Amazon',
    'shops.ikea': 'IKEA',
    'shops.abyat': 'ABYAT',
    'shops.namshi': 'NAMSHI',
    'shops.trendyol': 'TRENDYOL',
    'shops.asos': 'ASOS',
    'shops.title': 'Shops',
    
    'settings.other': 'Other',
    
    // Dashboard/Analytics (continued)
    'dashboard.title': 'Analytics',
    'dashboard.description': 'Track your product prices and savings',
    'dashboard.totalValue': 'Total Value of Products',
    'dashboard.latestPriceChanges': 'Latest price changes',
    'dashboard.keyMetrics': 'Key metrics at a glance',
    
    // Analytics Extended
    'analytics.addProductsPrompt': 'Add products to view their analytics',
    'analytics.noRecentChanges': 'No recent price changes',
    'analytics.savings': 'Savings',
    'analytics.avgPerProduct': 'Avg/Product',
    'analytics.bestDeal': 'Best Deal',
    'analytics.efficiency': 'Efficiency',
    'analytics.deepInsights': 'Deep insights into your price tracking performance',
    'analytics.storeAnalysis': 'Store Analysis',
    'analytics.priceMovement': 'Price Movement Analysis',
    'analytics.priceMovementDesc': 'Track how prices have changed over different time periods',
    'analytics.increases': 'increases',
    'analytics.decreases': 'decreases',
    'analytics.stable': 'stable',
    'analytics.products': 'products',
    
    // User roles
    'user.admin': 'ADMIN',
    'user.user': 'USER',
    'user.guest': 'GUEST',
    
    // Auth
    'auth.login': 'Log In',
    'auth.signOut': 'Sign Out',
    'auth.signOutSuccess': 'Signed out successfully',
    
    // Common UI
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.add': 'Add',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.update': 'Update',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.view': 'View',
    'common.close': 'Close',
    'common.open': 'Open',
    'common.create': 'Create',
    'common.submit': 'Submit',
    'common.confirm': 'Confirm',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.apply': 'Apply',
    'common.reset': 'Reset',
    'common.clear': 'Clear',
    'common.more': 'More...',
    'common.anyUrl': 'Any URL',
    'common.fullControl': 'Full Control',
    
    // Privacy Policy
    'privacy.title': 'Privacy Policy',
    'privacy.lastUpdated': 'Last updated: October 13, 2025',
    'privacy.intro.title': 'Introduction',
    'privacy.intro.content': 'Welcome to our price comparison platform. We are committed to protecting your privacy and ensuring the security of your personal information. This Privacy Policy explains how we collect, use, and safeguard your data when you use our services.',
    'privacy.infoCollect.title': 'Information We Collect',
    'privacy.infoCollect.account.title': 'Account Information',
    'privacy.infoCollect.account.content': 'When you create an account, we collect your email address, username, and password. This information is used to provide you with access to our services and personalize your experience.',
    'privacy.infoCollect.usage.title': 'Usage Data',
    'privacy.infoCollect.usage.content': 'We collect information about how you interact with our platform, including products you search for, prices you track, and stores you visit through our affiliate links.',
    'privacy.infoCollect.device.title': 'Device Information',
    'privacy.infoCollect.device.content': 'We automatically collect certain information about your device, including IP address, browser type, and operating system.',
    'privacy.howWeUse.title': 'How We Use Your Information',
    'privacy.howWeUse.item1': 'To provide and maintain our price comparison services',
    'privacy.howWeUse.item2': 'To track price changes and send you alerts',
    'privacy.howWeUse.item3': 'To improve our platform and user experience',
    'privacy.howWeUse.item4': 'To communicate with you about updates and features',
    'privacy.howWeUse.item5': 'To earn affiliate commissions when you make purchases through our links',
    'privacy.dataSharing.title': 'Data Sharing and Disclosure',
    'privacy.dataSharing.content': 'We do not sell your personal information. We may share your data with:',
    'privacy.dataSharing.item1': 'Service providers who help us operate our platform',
    'privacy.dataSharing.item2': 'Affiliate partners when you click on product links',
    'privacy.dataSharing.item3': 'Law enforcement when required by law',
    'privacy.security.title': 'Data Security',
    'privacy.security.content': 'We implement industry-standard security measures to protect your personal information. However, no method of transmission over the Internet is 100% secure, and we cannot guarantee absolute security.',
    'privacy.rights.title': 'Your Rights',
    'privacy.rights.content': 'You have the right to:',
    'privacy.rights.item1': 'Access your personal data',
    'privacy.rights.item2': 'Request correction of inaccurate data',
    'privacy.rights.item3': 'Request deletion of your account and data',
    'privacy.rights.item4': 'Opt-out of marketing communications',
    'privacy.cookies.title': 'Cookies and Tracking',
    'privacy.cookies.content': 'We use cookies and similar tracking technologies to improve your experience, analyze usage patterns, and track affiliate referrals. You can control cookies through your browser settings.',
    'privacy.changes.title': 'Changes to This Policy',
    'privacy.changes.content': 'We may update this Privacy Policy from time to time. We will notify you of any significant changes by posting the new policy on this page and updating the "Last Updated" date.',
    'privacy.contact.title': 'Contact Us',
    'privacy.contact.content': 'If you have questions about this Privacy Policy, please contact us at:',
    'privacy.contact.email': 'krolist.help@gmail.com',
    
    // Contact Us
    'contact.title': 'Contact Us',
    'contact.subtitle': 'We\'d love to hear from you. Get in touch with us!',
    'contact.email.title': 'Email',
    'contact.email.content': 'Send us an email and we\'ll get back to you as soon as possible.',
    'contact.twitter.title': 'Twitter/X',
    'contact.twitter.content': 'Follow us on X for updates',
    'contact.facebook.title': 'Facebook',
    'contact.comingSoon': 'Coming Soon',
    
    // Terms of Service
    'terms.title': 'Terms of Service',
    'terms.lastUpdated': 'Last updated: October 13, 2025',
    'terms.acceptance.title': 'Acceptance of Terms',
    'terms.acceptance.content': 'By accessing and using Krolist, you accept and agree to be bound by the terms and provision of this agreement. If you do not agree to these Terms of Service, please do not use our platform.',
    'terms.service.title': 'Description of Service',
    'terms.service.content': 'Krolist is a price comparison and product tracking platform that helps users find the best deals across multiple online stores. We provide product search, price tracking, and affiliate links to partner retailers including Noon, Amazon, Shein, and others.',
    'terms.accounts.title': 'User Accounts',
    'terms.accounts.content': 'To use certain features of our service, you must create an account. You agree to:',
    'terms.accounts.item1': 'Provide accurate and complete registration information',
    'terms.accounts.item2': 'Maintain the security of your password and account',
    'terms.accounts.item3': 'Accept responsibility for all activities under your account',
    'terms.accounts.item4': 'Notify us immediately of any unauthorized use',
    'terms.acceptable.title': 'Acceptable Use',
    'terms.acceptable.content': 'You agree not to use our service to:',
    'terms.acceptable.item1': 'Violate any laws or regulations',
    'terms.acceptable.item2': 'Infringe on intellectual property rights',
    'terms.acceptable.item3': 'Transmit malicious code or viruses',
    'terms.acceptable.item4': 'Attempt to gain unauthorized access to our systems',
    'terms.acceptable.item5': 'Engage in automated scraping without permission',
    'terms.affiliate.title': 'Affiliate Links and Commissions',
    'terms.affiliate.content': 'Our platform contains affiliate links to partner retailers. When you make a purchase through these links, we may earn a commission at no additional cost to you. These commissions help us maintain and improve our service.',
    'terms.pricing.title': 'Pricing Information',
    'terms.pricing.content': 'We strive to provide accurate pricing information, but prices are subject to change without notice. The final price is determined by the retailer at the time of purchase. We are not responsible for pricing errors on partner websites.',
    'terms.intellectual.title': 'Intellectual Property',
    'terms.intellectual.content': 'All content, features, and functionality of Krolist are owned by us and protected by copyright, trademark, and other intellectual property laws. You may not copy, modify, or distribute our content without permission.',
    'terms.limitation.title': 'Limitation of Liability',
    'terms.limitation.content': 'We provide our service "as is" without warranties. We are not liable for any indirect, incidental, or consequential damages arising from your use of our platform or purchases made through affiliate links.',
    'terms.termination.title': 'Termination',
    'terms.termination.content': 'We reserve the right to suspend or terminate your account at any time for violation of these terms or for any other reason. Upon termination, your right to use our service will immediately cease.',
    'terms.changes.title': 'Changes to Terms',
    'terms.changes.content': 'We may modify these Terms of Service at any time. Continued use of our service after changes constitutes acceptance of the modified terms.',
    'terms.contact.title': 'Contact Information',
    'terms.contact.content': 'For questions about these Terms of Service, please contact us at:',
    'terms.contact.email': 'krolist.help@gmail.com',
    
    // Admin categories
    'admin.categories': 'Categories',
    'admin.loginMessages': 'Login Messages',
    
    // Shopping Cart
    'cart.title': 'Shopping Cart',
    'cart.emptyCart': 'Your cart is empty',
    'cart.emptyGuide.description': 'Follow these simple steps to place your order:',
    'cart.emptyGuide.step1': 'Use the select button in the products page',
    'cart.emptyGuide.step2': 'Highlight the products you want',
    'cart.emptyGuide.step3': 'Add them to the cart and send the request to us',
    'cart.emptyGuide.step4': 'We will communicate with you between 1-3 days to arrange the shipping and payment',
    'cart.total': 'TOTAL',
    'cart.sendOrder': 'Send order to Krolist',
    'cart.orderDialog.title': 'Order through Krolist',
    'cart.orderDialog.fullName': 'Full Name',
    'cart.orderDialog.fullNamePlaceholder': 'Enter your full name',
    'cart.orderDialog.phone': 'Phone Number',
    'cart.orderDialog.phonePlaceholder': '+966 XX XXX XXXX',
    'cart.orderDialog.totalItems': 'Total Items',
    'cart.orderDialog.description': 'Admins will review your order and contact you shortly.',
    'cart.orderDialog.cancel': 'Cancel',
    'cart.orderDialog.submit': 'Submit Order',
    'cart.orderDialog.submitting': 'Submitting...',
    'cart.orderDialog.namePhoneRequired': 'Please provide your name and phone number',
    'cart.orderDialog.success': 'Order submitted successfully! Admins will contact you soon.',
    'cart.orderDialog.error': 'Failed to submit order',
    'cart.toast.openingStores': 'Opening stores in new tabs',
    'cart.itemsAdded': '{count} item(s) added to cart',
    
    // Footer
    'privacyPolicy': 'Privacy Policy',
    'termsOfService': 'Terms of Service',
    'contactUs': 'Contact Us',
    
    // Auth Modal
    'auth.welcomeTo': 'Welcome to Krolist',
    'auth.collectionOfCool': 'collection of cool products and more',
    'auth.signIn': 'Sign In',
    'auth.signUp': 'Sign Up',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.username': 'Username',
    'auth.enterEmail': 'Enter your email',
    'auth.enterPassword': 'Enter your password',
    'auth.enterUsername': 'Enter your username',
    'auth.rememberMe': 'Remember me',
    'auth.pleaseWait': 'Please wait...',
    'auth.createAccount': 'Create Account',
    'auth.accountCreated': 'Account created! Please check your email to verify.',
    'auth.welcomeBack': 'Welcome back!',
    'auth.invalidEmail': 'Invalid email address',
    'auth.usernameMin': 'Username must be at least 3 characters',
    'auth.passwordMin': 'Password must be at least 6 characters',
    
    // PWA Install
    'pwa.installApp': 'Install App',
    'pwa.installKrolist': 'Install Krolist!',
    'pwa.installDescription': 'Get instant notifications and faster experience. Free to install!',
    'pwa.install': 'Install',
    'pwa.later': 'Later',
    'pwa.howToInstall': 'How to Install',
    'pwa.gotIt': 'Got it!',
    'pwa.usersInstalled': 'users installed',
    'pwa.installSteps': 'Installation Steps',
    'pwa.step': 'Step',
    'pwa.of': 'of',
    
    // Image Cropper
    'promo.cropImage': 'Crop Image',
    'promo.applyCrop': 'Apply Crop',
    'processing': 'Processing...',
    
    // Notifications
    'notifications.title': 'Notifications',
    'notifications.noNotifications': 'No notifications',
    'notifications.notification': 'notification',
    'notifications.notifications': 'notifications',
    'notifications.clear': 'Clear',
    'notifications.allCaughtUp': 'All caught up!',
    'notifications.priceDropsWillAppear': 'Price drops and new deals will appear here',
    
    // Home page
    'home.home': 'Home',

    // Donation
    'donation.title': 'Support Krolist',
    'donation.subtitle': 'Help us keep Krolist free and ad-free',
    
    // Events
    'events.title': 'Events',
    'events.noEvents': 'No upcoming events',
    
    // Search
    'search.title': 'Search Products',
    'search.searching': 'Searching...',
    'search.noResults': 'No results found',
    'search.tryDifferent': 'Try different keywords',
    
    // My Orders
    'orders.title': 'My Orders',
    'orders.noOrders': 'No orders yet',
    'orders.status': 'Status',
    'orders.date': 'Date',
    'orders.total': 'Total',
    'orders.items': 'Items',
    'orders.pending': 'Pending',
    'orders.confirmed': 'Confirmed',
    'orders.shipped': 'Shipped',
    'orders.delivered': 'Delivered',
    'orders.cancelled': 'Cancelled',
  },
  ar: {
    // Common
    'loading': 'جاري التحميل...',
    'error': 'خطأ',
    'save': 'حفظ',
    'cancel': 'إلغاء',
    'success': 'نجح',
    'featured': 'مميز',
    'add': 'إضافة',
    'edit': 'تعديل',
    'delete': 'حذف',
    'remove': 'إزالة',
    'update': 'تحديث',
    'search': 'بحث',
    'filter': 'تصفية',
    'view': 'عرض',
    'close': 'إغلاق',
    'open': 'فتح',
    'create': 'إنشاء',
    'submit': 'إرسال',
    'confirm': 'تأكيد',
    'back': 'رجوع',
    'next': 'التالي',
    'apply': 'تطبيق',
    'reset': 'إعادة تعيين',
    'clear': 'مسح',
    
    // Navigation
    'nav.dashboard': 'لوحة التحكم',
    'nav.products': 'المنتجات',
    'nav.analytics': 'التحليلات',
    'nav.news': 'الأخبار والتحديثات',
    'nav.events': 'الفعاليات',
    'nav.promoCodes': 'أكواد الخصم',
    'nav.donation': 'دعم المطور',
    'nav.myOrders': 'طلباتي',
    'nav.settings': 'الإعدادات',
    'nav.categories': 'الفئات',
    'nav.articles': 'المقالات',
    'nav.addProduct': 'إضافة منتج',
    
    // Dashboard
    'dashboard.welcome': 'مرحباً بك في متتبع الأسعار',
    'dashboard.subtitle': 'تابع منتجاتك المفضلة ولا تفوت أي عرض',
    'dashboard.totalProducts': 'إجمالي المنتجات',
    'dashboard.priceDrops': 'انخفاض الأسعار',
    'dashboard.priceIncreases': 'ارتفاع الأسعار',
    'dashboard.totalAmount': 'المبلغ الإجمالي للمنتجات',
    'dashboard.watching': 'قيد المتابعة',
    'dashboard.recentAlerts': 'تغيير الأسعار الحديث',
    'dashboard.latestChanges': 'آخر تغييرات الأسعار على منتجاتك المتابعة',
    'dashboard.overview': 'نظرة عامة',
    
    // Products
    'products.title': 'منتجاتك',
    'products.subtitle': 'تابع وأدر منتجاتك المفضلة',
    'products.noProducts': 'لا توجد منتجات متابعة حتى الآن',
    'products.startTracking': 'ابدأ بمتابعة المنتجات لرؤيتها هنا',
    'products.viewDetails': 'عرض التفاصيل',
    'products.searchPlaceholder': 'البحث في المنتجات أو المتاجر أو الفئات...',
    'products.noResults': 'لم يتم العثور على منتجات',
    'products.noResultsDesc': 'جرب تعديل مصطلحات البحث',
    'products.delete': 'حذف',
    'products.currency': 'العملة',
    'products.refresh': 'تحديث',
    'products.edit': 'تعديل',
    'products.description': 'استمتع بجودة صوت غامرة مع إلغاء الضوضاء.',
    'products.updated': 'تم التحديث',
    'products.showHistory': 'عرض السجل',
    'products.priceDetails': 'تفاصيل السعر',
    'products.recordedHistory': 'سجل الأسعار المسجل خلال الـ 7 أشهر الماضية',
    'products.highest': 'الأعلى',
    'products.lowest': 'الأدنى',
    'products.original': 'الأصلي',
    'products.deleteSuccess': 'تم حذف المنتج بنجاح',
    'products.currencyChanged': 'تم تغيير العملة بنجاح',
    'products.editSuccess': 'تم تحديث المنتج بنجاح',
    'products.changeCurrency': 'تغيير العملة',
    'products.selectCurrency': 'اختر العملة لهذا المنتج',
    'products.editProduct': 'تعديل المنتج',
    'products.select': 'إضافة للسلة',
    'products.cancelSelection': 'إلغاء',
    'products.addToCart': 'إضافة للسلة',
    'products.selectedItems': 'عناصر محددة',
    'products.selectSameStore': 'يرجى تحديد المنتجات من نفس المتجر فقط',
    'products.editDescription': 'قم بتحديث تفاصيل المنتج أدناه',
    'products.productTitle': 'عنوان المنتج',
    'products.enterTitle': 'أدخل عنوان المنتج',
    'products.productDescription': 'وصف المنتج',
    'products.enterDescription': 'أدخل وصف المنتج',
    'products.imageUrl': 'رابط الصورة',
    'products.enterImageUrl': 'أدخل رابط الصورة',
    'products.currentPrice': 'السعر الحالي',
    'products.enterPrice': 'أدخل السعر',
    'products.addProduct': 'إضافة منتج',
    'products.addProductDesc': 'اختر كيف تريد إضافة منتج للمتابعة',
    'products.searchForProducts': 'البحث عن المنتجات',
    'products.searchProductsDesc': 'ابحث في متاجر متعددة وقارن الأسعار من بائعين مختلفين',
    'products.more': 'المزيد...',
    'products.addManually': 'إضافة يدوياً',
    'products.addManuallyDesc': 'الصق رابط المنتج وسنملأ التفاصيل تلقائياً، أو أدخل كل شيء يدوياً',
    'products.anyURL': 'أي رابط',
    'products.fullControl': 'تحكم كامل',
    'products.displayMode': 'العرض',
    'products.fullImage': 'الصورة كاملة',
    'products.cropped': 'مقصوصة',
    'products.history': 'السجل',
    
    // Settings
    'settings.title': 'الإعدادات',
    'settings.subtitle': 'إدارة تفضيلات حسابك وإعدادات التطبيق',
    'settings.languageRegion': 'اللغة والمنطقة',
    'settings.languageDesc': 'تكوين لغتك المفضلة والعملة الافتراضية',
    'settings.language': 'اللغة',
    'settings.currency': 'العملة الافتراضية',
    'settings.notifications': 'الإشعارات',
    'settings.notificationsDesc': 'اختر الإشعارات التي تريد استقبالها',
    'settings.enableNotifications': 'تمكين الإشعارات',
    'settings.enableNotificationsDesc': 'استقبل إشعارات حول تغييرات الأسعار والتحديثات',
    'settings.priceDropAlerts': 'تنبيهات انخفاض الأسعار',
    'settings.priceDropAlertsDesc': 'احصل على إشعار عندما تنخفض أسعار المنتجات المتابعة',
    'settings.weeklyReports': 'التقارير الأسبوعية',
    'settings.weeklyReportsDesc': 'استقبل ملخصات أسبوعية لمنتجاتك المتابعة',
    'settings.appearance': 'المظهر',
    'settings.appearanceDesc': 'انقر للتبديل بين الوضع الفاتح والداكن',
    'settings.theme': 'السمة',
    'settings.account': 'الحساب',
    'settings.accountDesc': 'إدارة معلومات حسابك',
    'settings.email': 'البريد الإلكتروني',
    'settings.displayName': 'الاسم المعروض',
    'settings.saveSettings': 'حفظ الإعدادات',
    'settings.settingsSaved': 'تم حفظ الإعدادات',
    'settings.settingsSavedDesc': 'تم تحديث تفضيلاتك بنجاح.',
    'settings.undertoneColor': 'لون النغمة',
    'settings.selectUndertone': 'اختر النغمة',
    'settings.undertone.orange': 'برتقالي',
    'settings.undertone.blue': 'أزرق',
    'settings.undertone.green': 'أخضر',
    'settings.undertone.purple': 'بنفسجي',
    'settings.undertone.red': 'أحمر',
    'settings.undertone.custom': 'مخصص',
    'settings.imageZoom': 'تكبير الصورة عند التمرير',
    'settings.imageZoomDesc': 'تفعيل تأثير التكبير',
    'settings.carouselSpeed': 'سرعة التمرير التلقائي',
    'settings.carouselSpeedDesc': 'أقل = أسرع',
    'settings.titleScrollSpeed': 'سرعة تمرير عنوان المنتج',
    'settings.customHue': 'درجة اللون المخصصة',
    'settings.languageCurrency': 'اللغة والعملة',
    'settings.username': 'اسم المستخدم',
    'settings.usernamePlaceholder': 'اسم المستخدم الخاص بك',
    'settings.updating': 'جاري التحديث...',
    'settings.updateAccount': 'تحديث الحساب',
    'settings.profileUpdated': 'تم تحديث الملف الشخصي بنجاح!',
    'settings.profileUpdatedEmail': 'تم تحديث الملف الشخصي! يرجى التحقق من بريدك الإلكتروني الجديد لتأكيد التغيير.',
    'settings.failedUpdate': 'فشل تحديث الملف الشخصي',
    'settings.notSupported': 'غير مدعوم',
    'settings.browserNoNotifications': 'المتصفح لا يدعم الإشعارات',
    'settings.notificationsEnabled': 'تم تفعيل الإشعارات',
    'settings.notifiedAboutUpdates': 'سيتم إعلامك بالتحديثات الجديدة',
    'settings.appInfo': 'معلومات التطبيق',
    'settings.versionUpdates': 'الإصدار والتحديثات',
    'settings.currentVersion': 'الإصدار الحالي',
    'settings.installUpdate': 'تثبيت التحديث',
    'settings.upToDate': 'أحدث إصدار',
    'settings.totalInstalls': 'عدد التثبيتات',
    'settings.usersInstalled': 'المستخدمون الذين قاموا بتثبيت التطبيق',
    'settings.updateNotifications': 'إشعارات التحديثات',
    'settings.updateNotificationsDesc': 'احصل على إشعار عند توفر تحديث جديد',
    'settings.enabled': 'مفعل',
    'settings.enable': 'تفعيل',
    'settings.promoAlerts': 'تنبيهات أكواد الخصم',
    'settings.promoAlertsDesc': 'احصل على إشعارات عن أكواد الخصم والعروض الجديدة',
    'settings.appUpdateAlerts': 'تنبيهات تحديث التطبيق',
    'settings.appUpdateAlertsDesc': 'احصل على إشعار عند توفر ميزات جديدة',
    'settings.eventReminders': 'تذكيرات الفعاليات',
    'settings.eventRemindersDesc': 'تذكير بفعاليات التسوق مثل الجمعة البيضاء',
    'settings.orderUpdates': 'تحديثات الطلبات',
    'settings.orderUpdatesDesc': 'احصل على إشعارات عن تغييرات حالة طلباتك',
    'settings.articleAlerts': 'تنبيهات المقالات الجديدة',
    'settings.articleAlertsDesc': 'احصل على إشعار عند نشر مقالات جديدة',
    
    // Products Page
    'products.myProducts': 'منتجاتي',
    'products.featuredProducts': 'منتجات مميزة',
    'products.krolistSelections': 'اختيارات كروليست',
    'products.expand': 'توسيع',
    'products.collapse': 'طي',
    
    // Categories
    'categories.title': 'الفئات',
    'categories.subtitle': 'تصفح المنتجات حسب الفئة',
    'categories.empty': 'لا توجد فئات متاحة حتى الآن',
    'categories.viewAll': 'عرض الكل',
    'categories.items': 'عناصر',
    
    // Promo Codes Page
    'promo.title': 'أكواد الخصم',
    'promo.subtitle': 'إدارة مجموعتك من أكواد الخصم والقسائم',
    'promo.addNew': 'إضافة كود خصم جديد',
    'promo.addNewDesc': 'احفظ أكواد الخصم التي تجدها على الإنترنت للوصول السهل عند التسوق',
    'promo.code': 'كود الخصم',
    'promo.codePlaceholder': 'SAVE20',
    'promo.shop': 'المتجر',
    'promo.selectShop': 'اختر متجراً',
    'promo.customShopName': 'اسم المتجر المخصص',
    'promo.enterShopName': 'أدخل اسم المتجر',
    'promo.description': 'الوصف',
    'promo.descriptionPlaceholder': 'خصم 20% على الإلكترونيات',
    'promo.addCode': 'إضافة الكود',
    'promo.codeCopied': 'تم نسخ الكود!',
    'promo.codeCopiedDesc': 'تم نسخ كود الخصم إلى الحافظة',
    'promo.authRequired': 'مطلوب تسجيل الدخول',
    'promo.signInToAdd': 'يرجى تسجيل الدخول لإضافة أكواد الخصم',
    'promo.missingInfo': 'معلومات ناقصة',
    'promo.fillAllFields': 'يرجى ملء جميع الحقول المطلوبة',
    'promo.limitReached': 'تم الوصول للحد الأقصى',
    'promo.limitReachedDesc': 'يمكنك حفظ ما يصل إلى 24 كود خصم فقط',
    'promo.codeAdded': 'تمت إضافة كود الخصم!',
    'promo.codeAddedDesc': 'تم حفظ كود الخصم في مجموعتك',
    'promo.codeUpdated': 'تم تحديث كود الخصم!',
    'promo.changesSaved': 'تم حفظ التغييرات',
    'promo.codeDeleted': 'تم حذف كود الخصم',
    'promo.codeDeletedDesc': 'تمت إزالة كود الخصم من مجموعتك',
    'promo.failedToLoad': 'فشل تحميل أكواد الخصم',
    'promo.failedToAdd': 'فشل إضافة كود الخصم',
    'promo.failedToUpdate': 'فشل تحديث كود الخصم',
    'promo.failedToDelete': 'فشل حذف كود الخصم',
    'promo.reusable': 'قابل للاستخدام المتكرر',
    'promo.oneTimeUse': 'استخدام لمرة واحدة',
    'promo.used': 'مستخدم',
    'promo.expires': 'ينتهي',
    'promo.copy': 'نسخ',
    'promo.editPromo': 'تعديل كود الخصم',
    'promo.editPromoDesc': 'قم بتحديث تفاصيل كود الخصم أدناه',
    'promo.store': 'المتجر',
    'promo.makeReusable': 'جعله قابل للاستخدام المتكرر',
    'promo.saveChanges': 'حفظ التغييرات',
    'promo.noPersonalCodes': 'لا توجد أكواد خصم شخصية حتى الآن',
    'promo.startSaving': 'ابدأ بحفظ أكواد الخصم التي تجدها على الإنترنت للوصول السهل عند التسوق',
    'promo.wantToSave': 'هل تريد حفظ أكواد الخصم الخاصة بك؟',
    'promo.createAccountToSave': 'أنشئ حساباً لحفظ وإدارة مجموعة أكواد الخصم الشخصية الخاصة بك. انقر على أيقونة المستخدم في أعلى اليمين للتسجيل أو تسجيل الدخول.',
    'promo.expired': 'منتهي الصلاحية',
    'promo.expiresToday': 'ينتهي اليوم',
    'promo.dayLeft': 'يوم متبقي',
    'promo.daysLeft': 'أيام متبقية',
    'promo.unknown': 'غير معروف',
    'promo.expirationDate': 'تاريخ الانتهاء',
    'promo.expirationHint': 'اتركه فارغاً لمدة سنة',
    'promo.usageType': 'نوع الاستخدام',
    'promo.storeImage': 'صورة المتجر',
    'promo.addImage': 'إضافة',
    'promo.changeImage': 'تغيير',
    'promo.saving': 'جاري الحفظ...',
    
    
    // Common
    'common.save': 'حفظ',
    'common.cancel': 'إلغاء',
    'common.add': 'إضافة',
    'common.edit': 'تعديل',
    'common.delete': 'حذف',
    'common.update': 'تحديث',
    'common.search': 'بحث',
    'common.filter': 'تصفية',
    'common.view': 'عرض',
    'common.close': 'إغلاق',
    'common.open': 'فتح',
    'common.create': 'إنشاء',
    'common.submit': 'إرسال',
    'common.confirm': 'تأكيد',
    'common.back': 'رجوع',
    'common.next': 'التالي',
    'common.apply': 'تطبيق',
    'common.reset': 'إعادة تعيين',
    'common.clear': 'مسح',
    'common.more': 'المزيد...',
    'common.anyUrl': 'أي رابط',
    'common.fullControl': 'تحكم كامل',
    'common.loading': 'جارٍ التحميل...',
    'common.error': 'خطأ',
    'common.success': 'نجح',
    
    // Auth
    'auth.login': 'تسجيل الدخول',
    'auth.signOut': 'تسجيل الخروج',
    'auth.signOutSuccess': 'تم تسجيل الخروج بنجاح',
    
    // User
    'user.guest': 'ضيف',
    
    // Privacy Policy
    'privacy.title': 'سياسة الخصوصية',
    'privacy.lastUpdated': 'آخر تحديث: 13 أكتوبر 2025',
    'privacy.intro.title': 'مقدمة',
    'privacy.intro.content': 'مرحبًا بك في منصة مقارنة الأسعار الخاصة بنا. نحن ملتزمون بحماية خصوصيتك وضمان أمان معلوماتك الشخصية. توضح سياسة الخصوصية هذه كيفية جمع بياناتك واستخدامها وحمايتها عند استخدام خدماتنا.',
    'privacy.infoCollect.title': 'المعلومات التي نجمعها',
    'privacy.infoCollect.account.title': 'معلومات الحساب',
    'privacy.infoCollect.account.content': 'عند إنشاء حساب، نجمع عنوان بريدك الإلكتروني واسم المستخدم وكلمة المرور. تُستخدم هذه المعلومات لتوفير الوصول إلى خدماتنا وتخصيص تجربتك.',
    'privacy.infoCollect.usage.title': 'بيانات الاستخدام',
    'privacy.infoCollect.usage.content': 'نجمع معلومات حول كيفية تفاعلك مع منصتنا، بما في ذلك المنتجات التي تبحث عنها والأسعار التي تتابعها والمتاجر التي تزورها من خلال روابط الشركاء.',
    'privacy.infoCollect.device.title': 'معلومات الجهاز',
    'privacy.infoCollect.device.content': 'نجمع تلقائيًا بعض المعلومات حول جهازك، بما في ذلك عنوان IP ونوع المتصفح ونظام التشغيل.',
    'privacy.howWeUse.title': 'كيف نستخدم معلوماتك',
    'privacy.howWeUse.item1': 'لتوفير وصيانة خدمات مقارنة الأسعار الخاصة بنا',
    'privacy.howWeUse.item2': 'لتتبع تغييرات الأسعار وإرسال تنبيهات لك',
    'privacy.howWeUse.item3': 'لتحسين منصتنا وتجربة المستخدم',
    'privacy.howWeUse.item4': 'للتواصل معك حول التحديثات والميزات',
    'privacy.howWeUse.item5': 'لكسب عمولات الشركاء عندما تقوم بعمليات شراء من خلال روابطنا',
    'privacy.dataSharing.title': 'مشاركة البيانات والإفصاح عنها',
    'privacy.dataSharing.content': 'لا نبيع معلوماتك الشخصية. قد نشارك بياناتك مع:',
    'privacy.dataSharing.item1': 'مزودي الخدمات الذين يساعدوننا في تشغيل منصتنا',
    'privacy.dataSharing.item2': 'شركاء التسويق بالعمولة عند النقر على روابط المنتجات',
    'privacy.dataSharing.item3': 'جهات إنفاذ القانون عند الطلب قانونيًا',
    'privacy.security.title': 'أمان البيانات',
    'privacy.security.content': 'نطبق تدابير أمنية معيارية في الصناعة لحماية معلوماتك الشخصية. ومع ذلك، لا توجد طريقة نقل عبر الإنترنت آمنة بنسبة 100٪، ولا يمكننا ضمان الأمان المطلق.',
    'privacy.rights.title': 'حقوقك',
    'privacy.rights.content': 'لديك الحق في:',
    'privacy.rights.item1': 'الوصول إلى بياناتك الشخصية',
    'privacy.rights.item2': 'طلب تصحيح البيانات غير الدقيقة',
    'privacy.rights.item3': 'طلب حذف حسابك وبياناتك',
    'privacy.rights.item4': 'إلغاء الاشتراك في الاتصالات التسويقية',
    'privacy.cookies.title': 'ملفات تعريف الارتباط والتتبع',
    'privacy.cookies.content': 'نستخدم ملفات تعريف الارتباط وتقنيات التتبع المماثلة لتحسين تجربتك وتحليل أنماط الاستخدام وتتبع إحالات الشركاء. يمكنك التحكم في ملفات تعريف الارتباط من خلال إعدادات المتصفح.',
    'privacy.changes.title': 'التغييرات على هذه السياسة',
    'privacy.changes.content': 'قد نحدث سياسة الخصوصية هذه من وقت لآخر. سنخطرك بأي تغييرات كبيرة من خلال نشر السياسة الجديدة على هذه الصفحة وتحديث تاريخ "آخر تحديث".',
    'privacy.contact.title': 'اتصل بنا',
    'privacy.contact.content': 'إذا كان لديك أسئلة حول سياسة الخصوصية هذه، يرجى الاتصال بنا على:',
    'privacy.contact.email': 'krolist.help@gmail.com',
    
    // Contact Us
    'contact.title': 'اتصل بنا',
    'contact.subtitle': 'يسعدنا سماع رأيك. تواصل معنا!',
    'contact.email.title': 'البريد الإلكتروني',
    'contact.email.content': 'أرسل لنا بريدًا إلكترونيًا وسنعود إليك في أقرب وقت ممكن.',
    'contact.twitter.title': 'تويتر/إكس',
    'contact.twitter.content': 'تابعنا على إكس للحصول على التحديثات',
    'contact.facebook.title': 'فيسبوك',
    'contact.comingSoon': 'قريبًا',
    
    // Terms of Service
    'terms.title': 'شروط الخدمة',
    'terms.lastUpdated': 'آخر تحديث: 13 أكتوبر 2025',
    'terms.acceptance.title': 'قبول الشروط',
    'terms.acceptance.content': 'من خلال الوصول إلى واستخدام كروليست، فإنك تقبل وتوافق على الالتزام بشروط وأحكام هذه الاتفاقية. إذا كنت لا توافق على شروط الخدمة هذه، يرجى عدم استخدام منصتنا.',
    'terms.service.title': 'وصف الخدمة',
    'terms.service.content': 'كروليست هي منصة لمقارنة الأسعار وتتبع المنتجات تساعد المستخدمين في العثور على أفضل العروض عبر متاجر متعددة عبر الإنترنت. نوفر البحث عن المنتجات وتتبع الأسعار وروابط الشركاء لتجار التجزئة الشركاء بما في ذلك نون وأمازون وشي إن وغيرها.',
    'terms.accounts.title': 'حسابات المستخدمين',
    'terms.accounts.content': 'لاستخدام ميزات معينة من خدمتنا، يجب عليك إنشاء حساب. أنت توافق على:',
    'terms.accounts.item1': 'تقديم معلومات تسجيل دقيقة وكاملة',
    'terms.accounts.item2': 'الحفاظ على أمان كلمة المرور والحساب الخاص بك',
    'terms.accounts.item3': 'قبول المسؤولية عن جميع الأنشطة ضمن حسابك',
    'terms.accounts.item4': 'إخطارنا على الفور بأي استخدام غير مصرح به',
    'terms.acceptable.title': 'الاستخدام المقبول',
    'terms.acceptable.content': 'أنت توافق على عدم استخدام خدمتنا من أجل:',
    'terms.acceptable.item1': 'انتهاك أي قوانين أو لوائح',
    'terms.acceptable.item2': 'انتهاك حقوق الملكية الفكرية',
    'terms.acceptable.item3': 'نقل رموز ضارة أو فيروسات',
    'terms.acceptable.item4': 'محاولة الوصول غير المصرح به إلى أنظمتنا',
    'terms.acceptable.item5': 'الانخراط في الكشط الآلي بدون إذن',
    'terms.affiliate.title': 'روابط الشركاء والعمولات',
    'terms.affiliate.content': 'تحتوي منصتنا على روابط شركاء لتجار التجزئة الشركاء. عندما تقوم بعملية شراء من خلال هذه الروابط، قد نكسب عمولة دون أي تكلفة إضافية عليك. تساعدنا هذه العمولات في صيانة وتحسين خدمتنا.',
    'terms.pricing.title': 'معلومات التسعير',
    'terms.pricing.content': 'نسعى جاهدين لتوفير معلومات تسعير دقيقة، لكن الأسعار عرضة للتغيير دون إشعار. يتم تحديد السعر النهائي من قبل بائع التجزئة في وقت الشراء. نحن غير مسؤولين عن أخطاء التسعير على مواقع الشركاء.',
    'terms.intellectual.title': 'الملكية الفكرية',
    'terms.intellectual.content': 'جميع المحتويات والميزات ووظائف كروليست مملوكة لنا ومحمية بموجب قوانين حقوق النشر والعلامات التجارية وقوانين الملكية الفكرية الأخرى. لا يجوز لك نسخ محتوانا أو تعديله أو توزيعه دون إذن.',
    'terms.limitation.title': 'حدود المسؤولية',
    'terms.limitation.content': 'نوفر خدمتنا "كما هي" دون ضمانات. نحن غير مسؤولين عن أي أضرار غير مباشرة أو عرضية أو تبعية ناشئة عن استخدامك لمنصتنا أو المشتريات التي تتم من خلال روابط الشركاء.',
    'terms.termination.title': 'الإنهاء',
    'terms.termination.content': 'نحتفظ بالحق في تعليق أو إنهاء حسابك في أي وقت لانتهاك هذه الشروط أو لأي سبب آخر. عند الإنهاء، سينتهي حقك في استخدام خدمتنا على الفور.',
    'terms.changes.title': 'التغييرات على الشروط',
    'terms.changes.content': 'يجوز لنا تعديل شروط الخدمة هذه في أي وقت. يشكل الاستخدام المستمر لخدمتنا بعد التغييرات قبولًا للشروط المعدلة.',
    'terms.contact.title': 'معلومات الاتصال',
    'terms.contact.content': 'للأسئلة حول شروط الخدمة هذه، يرجى الاتصال بنا على:',
    'terms.contact.email': 'krolist.help@gmail.com',
    
    // Theme options
    'theme.light': 'فاتح',
    'theme.dark': 'داكن',
    'theme.system': 'النظام',
    
    // Languages
    'language.en': 'English',
    'language.ar': 'العربية',
    
    // Currencies
    'currency.USD': 'دولار أمريكي - USD',
    'currency.SAR': 'ريال سعودي - SAR',
    'currency.EGP': 'جنيه مصري - EGP',
    'currency.AED': 'درهم إماراتي - AED',

    // Analytics
    'analytics.trends': 'اتجاهات الأسعار',
    'analytics.stores': 'أداء المتاجر',
    'analytics.categories': 'الفئات',
    'analytics.patterns': 'أنماط الأسعار',
    'analytics.trendsDesc': 'تتبع حركات الأسعار عبر الزمن',
    'analytics.storesDesc': 'مقارنة وفورات وموثوقية المتاجر',
    'analytics.categoriesDesc': 'تحليل المنتجات حسب الفئة',
    'analytics.patternsDesc': 'اكتشف متى تنخفض الأسعار أكثر',
    'analytics.avgSavings': 'متوسط الوفورات',
    'analytics.reliability': 'الموثوقية',
    
    // UI Controls
    'ui.fontSize': 'حجم الخط',
    'ui.iconSize': 'حجم الأيقونات',
    'ui.display': 'العرض',
    'ui.displayDesc': 'تخصيص أحجام الخط والأيقونات',
    'ui.small': 'صغير',
    'ui.medium': 'متوسط',
    'ui.large': 'كبير',

    // Shop Management
    'settings.shopManagement': 'إدارة المتاجر',
    'settings.shopManagementDesc': 'تنظيم وتخصيص المتاجر المتتبعة',
    'settings.addNewShop': 'إضافة متجر جديد...',
    'settings.dragToReorder': 'اسحب لإعادة الترتيب',
    'status.active': 'نشط',
    'search.placeholder': 'البحث في المتاجر...',

    // Shops
    'shops.shein': 'شي إن',
    'shops.noon': 'نون',
    'shops.amazon': 'أمازون',
    'shops.ikea': 'إيكيا',
    'shops.abyat': 'أبيات',
    'shops.namshi': 'نمشي',
    'shops.trendyol': 'تريندي يول',
    'shops.asos': 'إيسوس',
    'shops.title': 'المتاجر',
    
    'settings.other': 'أخرى',
    
    // Admin Dashboard
    'admin.dashboard': 'لوحة تحكم المسؤول',
    'admin.dashboardDesc': 'إدارة محتوى وإعدادات كروليست',
    'admin.accessDenied': 'الوصول مرفوض',
    'admin.accessDeniedDesc': 'تحتاج إلى صلاحيات المسؤول للوصول إلى هذه الصفحة',
    'admin.krolistProducts': 'منتجات كروليست',
    'admin.krolistProductsDesc': 'إدارة اختيارات المنتجات المنسقة لجميع المستخدمين',
    'admin.promoCodes': 'أكواد الخصم',
    'admin.krolistPromoCodes': 'أكواد خصم كروليست',
    'admin.krolistPromoCodesDesc': 'إدارة أكواد الخصم المرئية لجميع المستخدمين',
    'admin.newsUpdates': 'الأخبار والتحديثات',
    'admin.newsUpdatesDesc': 'إدارة الأخبار والإعلانات',
    'admin.shopManagement': 'إدارة المتاجر',
    'admin.shopManagementDesc': 'إدارة المتاجر المتاحة وروابط الشراكة',
    'admin.addProduct': 'إضافة منتج',
    'admin.manualPrices': 'تحديث الأسعار',
    
    // Dashboard/Analytics (continued)
    'dashboard.title': 'التحليلات',
    'dashboard.description': 'تتبع أسعار منتجاتك ومدخراتك',
    'dashboard.totalValue': 'القيمة الإجمالية للمنتجات',
    'dashboard.latestPriceChanges': 'آخر تغييرات الأسعار',
    'dashboard.keyMetrics': 'المقاييس الرئيسية في لمحة',
    
    // Analytics Extended
    'analytics.addProductsPrompt': 'أضف منتجات لعرض تحليلاتها',
    'analytics.noRecentChanges': 'لا توجد تغييرات حديثة في الأسعار',
    'analytics.savings': 'التوفير',
    'analytics.avgPerProduct': 'المتوسط/منتج',
    'analytics.bestDeal': 'أفضل صفقة',
    'analytics.efficiency': 'الكفاءة',
    'analytics.deepInsights': 'رؤى عميقة حول أداء تتبع الأسعار',
    'analytics.storeAnalysis': 'تحليل المتاجر',
    'analytics.priceMovement': 'تحليل حركة الأسعار',
    'analytics.priceMovementDesc': 'تتبع كيف تغيرت الأسعار عبر فترات زمنية مختلفة',
    'analytics.increases': 'زيادات',
    'analytics.decreases': 'انخفاضات',
    'analytics.stable': 'مستقر',
    'analytics.products': 'منتجات',
    
    // User roles
    'user.admin': 'مسؤول',
    'user.user': 'مستخدم',
    
    // Admin categories
    'admin.categories': 'الفئات',
    'admin.loginMessages': 'رسائل تسجيل الدخول',
    
    // Shopping Cart
    'cart.title': 'عربة التسوق',
    'cart.emptyCart': 'عربة التسوق فارغة',
    'cart.emptyGuide.description': 'اتبع هذه الخطوات البسيطة لتقديم طلبك:',
    'cart.emptyGuide.step1': 'استخدم زر التحديد في صفحة المنتجات',
    'cart.emptyGuide.step2': 'حدد المنتجات التي تريدها',
    'cart.emptyGuide.step3': 'أضفها إلى السلة وأرسل الطلب إلينا',
    'cart.emptyGuide.step4': 'سنتواصل معك خلال 1-3 أيام لترتيب الشحن والدفع',
    'cart.total': 'الإجمالي',
    'cart.sendOrder': 'إرسال الطلب إلى كروليست',
    'cart.orderDialog.title': 'الطلب عبر كروليست',
    'cart.orderDialog.fullName': 'الاسم الكامل',
    'cart.orderDialog.fullNamePlaceholder': 'أدخل اسمك الكامل',
    'cart.orderDialog.phone': 'رقم الهاتف',
    'cart.orderDialog.phonePlaceholder': '+966 XX XXX XXXX',
    'cart.orderDialog.totalItems': 'إجمالي المنتجات',
    'cart.orderDialog.description': 'سيقوم المسؤولون بمراجعة طلبك والتواصل معك قريباً.',
    'cart.orderDialog.cancel': 'إلغاء',
    'cart.orderDialog.submit': 'إرسال الطلب',
    'cart.orderDialog.submitting': 'جارٍ الإرسال...',
    'cart.orderDialog.namePhoneRequired': 'يرجى تقديم اسمك ورقم هاتفك',
    'cart.orderDialog.success': 'تم إرسال الطلب بنجاح! سيتواصل معك المسؤولون قريباً.',
    'cart.orderDialog.error': 'فشل إرسال الطلب',
    'cart.toast.openingStores': 'فتح المتاجر في علامات تبويب جديدة',
    'cart.itemsAdded': 'تمت إضافة {count} منتج إلى السلة',
    
    // Footer
    'privacyPolicy': 'سياسة الخصوصية',
    'termsOfService': 'شروط الخدمة',
    'contactUs': 'اتصل بنا',
    
    // Auth Modal
    'auth.welcomeTo': 'مرحباً بك في كروليست',
    'auth.collectionOfCool': 'مجموعة من المنتجات الرائعة والمزيد',
    'auth.signIn': 'تسجيل الدخول',
    'auth.signUp': 'إنشاء حساب',
    'auth.email': 'البريد الإلكتروني',
    'auth.password': 'كلمة المرور',
    'auth.username': 'اسم المستخدم',
    'auth.enterEmail': 'أدخل بريدك الإلكتروني',
    'auth.enterPassword': 'أدخل كلمة المرور',
    'auth.enterUsername': 'أدخل اسم المستخدم',
    'auth.rememberMe': 'تذكرني',
    'auth.pleaseWait': 'يرجى الانتظار...',
    'auth.createAccount': 'إنشاء حساب',
    'auth.accountCreated': 'تم إنشاء الحساب! يرجى التحقق من بريدك الإلكتروني.',
    'auth.welcomeBack': 'مرحباً بعودتك!',
    'auth.invalidEmail': 'عنوان بريد إلكتروني غير صالح',
    'auth.usernameMin': 'يجب أن يكون اسم المستخدم 3 أحرف على الأقل',
    'auth.passwordMin': 'يجب أن تكون كلمة المرور 6 أحرف على الأقل',
    
    // PWA Install
    'pwa.installApp': 'تثبيت التطبيق',
    'pwa.installKrolist': 'ثبّت كروليست!',
    'pwa.installDescription': 'احصل على إشعارات فورية وتجربة أسرع. تثبيت مجاني!',
    'pwa.install': 'تثبيت',
    'pwa.later': 'لاحقاً',
    'pwa.howToInstall': 'كيفية التثبيت',
    'pwa.gotIt': 'فهمت!',
    'pwa.usersInstalled': 'مستخدم قاموا بالتثبيت',
    'pwa.installSteps': 'خطوات التثبيت',
    'pwa.step': 'خطوة',
    'pwa.of': 'من',
    
    // Image Cropper
    'promo.cropImage': 'قص الصورة',
    'promo.applyCrop': 'تطبيق القص',
    'processing': 'جارٍ المعالجة...',
    
    // Notifications
    'notifications.title': 'الإشعارات',
    'notifications.noNotifications': 'لا توجد إشعارات',
    'notifications.notification': 'إشعار',
    'notifications.notifications': 'إشعارات',
    'notifications.clear': 'مسح',
    'notifications.allCaughtUp': 'كل شيء جاهز!',
    'notifications.priceDropsWillAppear': 'ستظهر هنا تحديثات الأسعار والعروض الجديدة',
    
    // Home page
    'home.home': 'الرئيسية',

    // Donation
    'donation.title': 'دعم كروليست',
    'donation.subtitle': 'ساعدنا في إبقاء كروليست مجاني وبدون إعلانات',
    
    // Events
    'events.title': 'الفعاليات',
    'events.noEvents': 'لا توجد فعاليات قادمة',
    
    // Search
    'search.title': 'البحث عن المنتجات',
    'search.searching': 'جارٍ البحث...',
    'search.noResults': 'لم يتم العثور على نتائج',
    'search.tryDifferent': 'جرب كلمات مختلفة',
    
    // My Orders
    'orders.title': 'طلباتي',
    'orders.noOrders': 'لا توجد طلبات بعد',
    'orders.status': 'الحالة',
    'orders.date': 'التاريخ',
    'orders.total': 'الإجمالي',
    'orders.items': 'المنتجات',
    'orders.pending': 'قيد الانتظار',
    'orders.confirmed': 'تم التأكيد',
    'orders.shipped': 'تم الشحن',
    'orders.delivered': 'تم التوصيل',
    'orders.cancelled': 'ملغي',
  }
};

const currencySymbols: Record<Currency, string> = {
  USD: '$',
  SAR: '﷼',
  EGP: 'E£',
  AED: 'د.إ'
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    return (localStorage.getItem('language') as Language) || 'en';
  });

  const [currency, setCurrency] = useState<Currency>(() => {
    return (localStorage.getItem('currency') as Currency) || 'SAR';
  });

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
    // Update document direction for RTL languages
    document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = lang;
  };

  const handleSetCurrency = (curr: Currency) => {
    setCurrency(curr);
    localStorage.setItem('currency', curr);
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  const getCurrencySymbol = (curr?: Currency): string => {
    return currencySymbols[curr || currency];
  };

  // Set initial direction
  React.useEffect(() => {
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language]);

  return (
    <LanguageContext.Provider 
      value={{ 
        language, 
        currency, 
        setLanguage: handleSetLanguage, 
        setCurrency: handleSetCurrency, 
        t, 
        getCurrencySymbol 
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};